export const countryToLang: Record<string, string> = {
  VN: "vi",
  US: "en",
  FR: "fr",
  JP: "ja",
  KR: "ko",
  CN: "zh",
};

export const weatherTranslations: Record<string, Record<string, string>> = {
  "clear sky": {
    vi: "Trời quang",
    en: "Clear sky",
    fr: "Ciel dégagé",
    ja: "快晴",
    ko: "맑은 하늘",
    zh: "晴朗的天空",
  },
  "few clouds": {
    vi: "Ít mây",
    en: "Few clouds",
    fr: "Peu de nuages",
    ja: "少ない雲",
    ko: "구름 조금",
    zh: "少云",
  },
  "scattered clouds": {
    vi: "Mây rải rác",
    en: "Scattered clouds",
    fr: "Nuages épars",
    ja: "散在する雲",
    ko: "흩어진 구름",
    zh: "零散的云",
  },
  "broken clouds": {
    vi: "Mây vỡ",
    en: "Broken clouds",
    fr: "Nuages fragmentés",
    ja: "壊れた雲",
    ko: "부서진 구름",
    zh: "破碎的云",
  },
  "overcast clouds": {
    vi: "Nhiều mây",
    en: "Overcast clouds",
    fr: "Nuages couverts",
    ja: "曇り空",
    ko: "흐린 구름",
    zh: "阴云密布",
  },
  "light rain": {
    vi: "Mưa nhẹ",
    en: "Light rain",
    fr: "Pluie légère",
    ja: "小雨",
    ko: "약한 비",
    zh: "小雨",
  },
  "moderate rain": {
    vi: "Mưa vừa",
    en: "Moderate rain",
    fr: "Pluie modérée",
    ja: "適度な雨",
    ko: "보통 비",
    zh: "中雨",
  },
  "heavy intensity rain": {
    vi: "Mưa to",
    en: "Heavy rain",
    fr: "Pluie forte",
    ja: "激しい雨",
    ko: "강한 비",
    zh: "大雨",
  },
  "very heavy rain": {
    vi: "Mưa rất to",
    en: "Very heavy rain",
    fr: "Pluie très forte",
    ja: "非常に激しい雨",
    ko: "매우 강한 비",
    zh: "暴雨",
  },
  "extreme rain": {
    vi: "Mưa cực lớn",
    en: "Extreme rain",
    fr: "Pluie extrême",
    ja: "極端な雨",
    ko: "극심한 비",
    zh: "极端暴雨",
  },
  "freezing rain": {
    vi: "Mưa tuyết",
    en: "Freezing rain",
    fr: "Pluie verglaçante",
    ja: "氷雨",
    ko: "얼어붙는 비",
    zh: "冻雨",
  },
  "shower rain": {
    vi: "Mưa rào",
    en: "Shower rain",
    fr: "Averse de pluie",
    ja: "にわか雨",
    ko: "소나기",
    zh: "阵雨",
  },
  "thunderstorm": {
    vi: "Giông bão",
    en: "Thunderstorm",
    fr: "Orage",
    ja: "雷雨",
    ko: "천둥번개",
    zh: "雷暴",
  },
  "snow": {
    vi: "Tuyết",
    en: "Snow",
    fr: "Neige",
    ja: "雪",
    ko: "눈",
    zh: "雪",
  },
  "light snow": {
    vi: "Tuyết nhẹ",
    en: "Light snow",
    fr: "Neige légère",
    ja: "小雪",
    ko: "약한 눈",
    zh: "小雪",
  },
  "heavy snow": {
    vi: "Tuyết dày",
    en: "Heavy snow",
    fr: "Neige abondante",
    ja: "大雪",
    ko: "강한 눈",
    zh: "大雪",
  },
  "sleet": {
    vi: "Mưa tuyết",
    en: "Sleet",
    fr: "Grésil",
    ja: "みぞれ",
    ko: "진눈깨비",
    zh: "雨夹雪",
  },
  "mist": {
    vi: "Sương mù",
    en: "Mist",
    fr: "Brume",
    ja: "霧",
    ko: "안개",
    zh: "薄雾",
  },
  "smoke": {
    vi: "Khói",
    en: "Smoke",
    fr: "Fumée",
    ja: "煙",
    ko: "연기",
    zh: "烟雾",
  },
  "haze": {
    vi: "Mù",
    en: "Haze",
    fr: "Brume sèche",
    ja: "もや",
    ko: "실안개",
    zh: "霾",
  },
  "fog": {
    vi: "Sương mù dày",
    en: "Fog",
    fr: "Brouillard",
    ja: "濃霧",
    ko: "짙은 안개",
    zh: "浓雾",
  },
  "sand": {
    vi: "Cát",
    en: "Sand",
    fr: "Sable",
    ja: "砂",
    ko: "모래",
    zh: "沙尘",
  },
  "dust": {
    vi: "Bụi",
    en: "Dust",
    fr: "Poussière",
    ja: "ほこり",
    ko: "먼지",
    zh: "尘土",
  },
  "volcanic ash": {
    vi: "Tro núi lửa",
    en: "Volcanic ash",
    fr: "Cendres volcaniques",
    ja: "火山灰",
    ko: "화산재",
    zh: "火山灰",
  },
  "squalls": {
    vi: "Gió giật",
    en: "Squalls",
    fr: "Rafales",
    ja: "突風",
    ko: "돌풍",
    zh: "飑风",
  },
  "tornado": {
    vi: "Lốc xoáy",
    en: "Tornado",
    fr: "Tornade",
    ja: "竜巻",
    ko: "토네이도",
    zh: "龙卷风",
  }
};
